name : Pytest and pylint CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout my project ğŸ› ï¸

      - uses: actions/setup-python@v4
        name: Install python 3.10 ğŸ
        with:
          python-version: "3.10"

      - run:
          python -m pip install -r requirements.txt
        name: Install requirements ğŸ“

      - run:
          pytest .
        name: Pytest (Testing project) ğŸ“

      -run:
          python -m pylint .
        name: Pylint (Code coverage) ğŸ”